### ISSUE TITLE
关于谭冬生是否是谭震林之子的问题

### ISSUE THREAD

**Issue by qxkuo** [LuoSheng12345/zhao#4]
我倾向于不是，但也不太确定，这里提issue主要是想列明现有材料，讨论一下。

支持谭冬生是谭震林之子的材料：
1. [湖南红色记忆多媒体资源库](http://hnhsjy1.txhn.net/jcrw/qt/201611/t20161122_456995.htm)，摘录如下：

> 湖南攸县人，1940年出生于攸县莲塘坳乡春洲村一个农民家庭，原国务院副总理、全国人大常委会副委员长谭震林之子。1957年入攸县一中读书。1958年初参加中国人民解放军，历任战士、班长、排长、技师、参谋。1970年调总参谋部机关工作，先后任参谋、副处长、处长、主任、动员部副部长、部长等职。期间兼任中国红十字会理事、中央综合治理委员会委员、国防部征兵办公室主任。1996年任广州军区副司令员。1990年被授予少将军衔，1997被授予中将军衔。第八、十届全国人大代表，第十届全国人大财政经济委员会委员。

这条没有给出来源，不过网站是湖南省图书馆办的，已经是最靠谱的一个了。

否认谭冬生是谭震林之子的材料：
1. [实录：谭震林子女谭泾远、谭晓光访谈缅怀父亲 (5)](https://web.archive.org/web/20150508043925/http://dangshi.people.com.cn/GB/16046251.html)，相关部分摘录如下：

> \[谭泾远\]:1940年抗战非常的残酷，当时有的孩子一哭，有的时候是因为捂嘴，就把孩子捂死了。当时我父亲把我送到上海，一直到抗战胜利以后，1946年春天才把我从上海接回来。我父亲是38岁结的婚，39岁有的我，第一个孩子，作为他来讲当然是非常的稀罕。我回来的时候，他在开会。听说我回来就从楼上下来了，我见到他就哭的一塌糊涂，我哭着就要找送我来的阿婆。

这条是维基百科上儿女的参考条目，是谭震林儿子女儿的回忆。应该可信度比较高。这条说39岁有第一个孩子，谭震林出生于1902年，也就是1941年第一个孩子。可是谭冬生出生于1940年，对不上。
不过仔细看这个材料的话，谭震林应该不止有一子一女，部分网站提到他有[6个孩子](https://www.sohu.com/a/462264029_257291)。

2. 谭震林的生平很容易找，1940年前后如下：
> 新编的新四军开赴皖南抗日前线,时任第三支队副司令员的谭震林,在1938年夏秋至1940年春间率领第三支队挺进南陵、繁昌、铜陵地区。
> 1940年后,谭震林率部奔赴苏常太地区,创建东路抗日游击根据地。

而谭冬生1940年出生在[攸县莲塘坳乡春洲村一农民家庭](http://ren.richinfer.net/Celebrity/index803.html)，怎么看都对不上，地点不对，人物关系也不对。谭冬生生平的出处是《二十世纪湖南人物》，如果能找到原文应该就更确定了。

**Comment by LuoSheng12345** [comment]
我认为这个问题不好说，我倾向于不对原本的数据库进行修改。

这个项目的目标是更新原数据库中明显出问题的地方，比如XXX死了这一类的，以及补充不全的人员。更改有争议的数据并非我一开始对这个项目的设想。

感谢提出这个Issue，这个issue的链接我会放到看板里面，以供以后的人参考。
